import type { Analyte } from '../types';

const COUNT_UNITS = [
  { unit: '10^3/µL', toCanonical: 1000 },
  { unit: '10^9/L', toCanonical: 1000 },
];

const pct = (id: string, name: string, aliases: string[]): Analyte => ({
  id,
  name,
  aliases,
  category: 'ematologia',
  specimen: 'blood',
  kind: 'numeric',
  canonicalUnit: '%',
  plausible: { min: 0, max: 100 },
});

const abs = (id: string, name: string, aliases: string[]): Analyte => ({
  id,
  name,
  aliases,
  category: 'ematologia',
  specimen: 'blood',
  kind: 'numeric',
  canonicalUnit: '/µL',
  units: COUNT_UNITS,
  plausible: { min: 0, max: 50000 },
});

export const hematology: Analyte[] = [
  {
    id: 'rbc',
    name: 'Globuli rossi',
    aliases: ['Globuli rossi', 'Eritrociti', 'RBC', 'Emazie'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '/µL',
    units: [
      { unit: '10^6/µL', toCanonical: 1e6 },
      { unit: '10^12/L', toCanonical: 1e6 },
    ],
    plausible: { min: 1e6, max: 1e7 },
  },
  {
    id: 'hemoglobin',
    name: 'Emoglobina',
    aliases: ['Emoglobina', 'Hb', 'HGB'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'g/dL',
    units: [{ unit: 'g/L', toCanonical: 0.1 }],
    plausible: { min: 3, max: 25 },
  },
  {
    id: 'hematocrit',
    name: 'Ematocrito',
    aliases: ['Valore Ematocrito', 'Ematocrito', 'HCT', 'Ht'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '%',
    plausible: { min: 10, max: 70 },
  },
  {
    id: 'mcv',
    name: 'MCV',
    aliases: ['MCV', 'Volume corpuscolare medio'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'fL',
    plausible: { min: 50, max: 150 },
  },
  {
    id: 'mch',
    name: 'MCH',
    aliases: ['MCH', 'Contenuto medio di emoglobina'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg',
    plausible: { min: 15, max: 45 },
  },
  {
    id: 'mchc',
    name: 'MCHC',
    aliases: ['MCHC', 'Concentrazione media di emoglobina'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'g/dL',
    units: [{ unit: 'g/L', toCanonical: 0.1 }],
    plausible: { min: 25, max: 40 },
  },
  {
    id: 'rdw',
    name: 'RDW',
    aliases: ['RDW', 'RDW-CV'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '%',
    plausible: { min: 8, max: 30 },
  },
  {
    id: 'platelets',
    name: 'Piastrine',
    aliases: ['Piastrine', 'PLT', 'Trombociti'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '/µL',
    units: COUNT_UNITS,
    plausible: { min: 5000, max: 2000000 },
  },
  {
    id: 'mpv',
    name: 'MPV',
    aliases: ['MPV', 'Volume piastrinico medio'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'fL',
    plausible: { min: 4, max: 20 },
  },
  {
    id: 'wbc',
    name: 'Globuli bianchi',
    aliases: ['Globuli bianchi', 'Leucociti', 'WBC'],
    category: 'ematologia',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '/µL',
    units: COUNT_UNITS,
    plausible: { min: 500, max: 100000 },
  },
  pct('neutrophils-pct', 'Neutrofili %', ['Neutrofili', 'Neutrofili %', 'Granulociti neutrofili']),
  pct('lymphocytes-pct', 'Linfociti %', ['Linfociti', 'Linfociti %']),
  pct('monocytes-pct', 'Monociti %', ['Monociti', 'Monociti %']),
  pct('eosinophils-pct', 'Eosinofili %', ['Eosinofili', 'Eosinofili %', 'Granulociti eosinofili']),
  pct('basophils-pct', 'Basofili %', ['Basofili', 'Basofili %', 'Granulociti basofili']),
  pct('reticulocytes-pct', 'Reticolociti %', ['Reticolociti', 'Reticolociti %']),
  abs('neutrophils-abs', 'Neutrofili', ['Neutrofili', 'Neutrofili #', 'Granulociti neutrofili']),
  abs('lymphocytes-abs', 'Linfociti', ['Linfociti', 'Linfociti #']),
  abs('monocytes-abs', 'Monociti', ['Monociti', 'Monociti #']),
  abs('eosinophils-abs', 'Eosinofili', ['Eosinofili', 'Eosinofili #', 'Granulociti eosinofili']),
  abs('basophils-abs', 'Basofili', ['Basofili', 'Basofili #', 'Granulociti basofili']),
];
