import type { Analyte } from '../types';

export const inflammation: Analyte[] = [
  {
    id: 'esr',
    name: 'VES',
    aliases: ['VES', 'Velocità di eritrosedimentazione', 'Velocita di eritrosedimentazione'],
    category: 'infiammazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mm/h',
  },
  {
    id: 'crp',
    name: 'Proteina C reattiva',
    aliases: ['Proteina C reattiva', 'PCR', 'Proteina C reattiva ad alta sensibilità'],
    category: 'infiammazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mg/L',
    units: [{ unit: 'mg/dL', toCanonical: 10 }],
  },
  {
    id: 'procalcitonin',
    name: 'Procalcitonina',
    aliases: ['Procalcitonina', 'PCT'],
    category: 'infiammazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
  },
];

export const coagulation: Analyte[] = [
  {
    id: 'pt-inr',
    name: 'INR',
    aliases: ['INR', 'PT INR', 'Tempo di protrombina INR'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
  },
  {
    id: 'pt-pct',
    name: 'Attività protrombinica',
    aliases: ['Attività protrombinica', 'Attivita protrombinica', 'PT %', 'Tempo di protrombina %'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: '%',
  },
  {
    id: 'pt-sec',
    name: 'Tempo di protrombina',
    aliases: ['Tempo di protrombina', 'PT', 'PT sec'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 's',
  },
  {
    id: 'aptt',
    name: 'aPTT',
    aliases: ['aPTT', 'PTT', 'Tempo di tromboplastina parziale attivata'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 's',
  },
  {
    id: 'aptt-ratio',
    name: 'aPTT ratio',
    aliases: ['aPTT ratio', 'PTT ratio'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
  },
  {
    id: 'fibrinogen',
    name: 'Fibrinogeno',
    aliases: ['Fibrinogeno'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mg/dL',
    units: [{ unit: 'g/L', toCanonical: 100 }],
  },
  {
    id: 'd-dimer',
    name: 'D-dimero',
    aliases: ['D-dimero', 'D dimero', 'XDP'],
    category: 'coagulazione',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'µg/L', toCanonical: 1 }],
    plausible: { min: 10, max: 100000 },
  },
];

const fraction = (id: string, name: string, aliases: string[]): Analyte => ({
  id,
  name,
  aliases,
  category: 'proteine',
  specimen: 'blood',
  kind: 'numeric',
  canonicalUnit: '%',
  plausible: { min: 0, max: 100 },
});

export const proteins: Analyte[] = [
  {
    id: 'total-protein',
    name: 'Proteine totali',
    aliases: ['Proteine totali', 'Protidemia', 'Protidemia totale'],
    category: 'proteine',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'g/dL',
    units: [{ unit: 'g/L', toCanonical: 0.1 }],
  },
  {
    id: 'albumin',
    name: 'Albumina',
    aliases: ['Albumina', 'Albuminemia'],
    category: 'proteine',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'g/dL',
    units: [{ unit: 'g/L', toCanonical: 0.1 }],
  },
  fraction('albumin-pct', 'Albumina %', ['Albumina', 'Albumina %']),
  fraction('alpha1-pct', 'Alfa 1 globuline %', ['Alfa 1', 'Alfa 1 globuline', 'Alfa1 globuline']),
  fraction('alpha2-pct', 'Alfa 2 globuline %', ['Alfa 2', 'Alfa 2 globuline', 'Alfa2 globuline']),
  fraction('beta1-pct', 'Beta 1 globuline %', ['Beta 1', 'Beta 1 globuline', 'Beta1 globuline']),
  fraction('beta2-pct', 'Beta 2 globuline %', ['Beta 2', 'Beta 2 globuline', 'Beta2 globuline']),
  fraction('gamma-pct', 'Gamma globuline %', ['Gamma', 'Gamma globuline', 'Gammaglobuline']),
  {
    id: 'ag-ratio',
    name: 'Rapporto albumina/globuline',
    aliases: ['Rapporto A/G', 'Rapporto albumina globuline', 'A/G'],
    category: 'proteine',
    specimen: 'blood',
    kind: 'numeric',
  },
];

export const other: Analyte[] = [
  {
    id: 'psa-total',
    name: 'PSA totale',
    aliases: ['PSA', 'PSA totale', 'Antigene prostatico specifico'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'µg/L', toCanonical: 1 }],
  },
  {
    id: 'psa-free',
    name: 'PSA libero',
    aliases: ['PSA libero', 'PSA free'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'µg/L', toCanonical: 1 }],
  },
  {
    id: 'cpk',
    name: 'CPK',
    aliases: ['CPK', 'CK', 'Creatinchinasi', 'Creatinfosfochinasi'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'U/L',
    plausible: { min: 0, max: 100000 },
  },
  {
    id: 'amylase',
    name: 'Amilasi',
    aliases: ['Amilasi', 'Amilasemia'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'U/L',
    plausible: { min: 0, max: 100000 },
  },
  {
    id: 'lipase',
    name: 'Lipasi',
    aliases: ['Lipasi', 'Lipasemia'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'U/L',
    plausible: { min: 0, max: 100000 },
  },
  {
    id: 'homocysteine',
    name: 'Omocisteina',
    aliases: ['Omocisteina', 'Omocisteinemia'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'µmol/L',
  },
  {
    id: 'ige-total',
    name: 'IgE totali',
    aliases: ['IgE totali', 'IgE', 'PRIST'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'UI/mL',
  },
  {
    id: 'rheumatoid-factor',
    name: 'Fattore reumatoide',
    aliases: ['Fattore reumatoide', 'Reuma test', 'FR'],
    category: 'altro',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'UI/mL',
  },
];
