import type { Analyte } from '../types';

const enzyme = (
  id: string,
  name: string,
  aliases: string[],
  category: Analyte['category'] = 'epatica',
): Analyte => ({
  id,
  name,
  aliases,
  category,
  specimen: 'blood',
  kind: 'numeric',
  canonicalUnit: 'U/L',
  plausible: { min: 0, max: 100000 },
});

// bilirubin: 1 µmol/L = 0.05848 mg/dL
const BILIRUBIN_UNITS = [{ unit: 'µmol/L', toCanonical: 0.05848 }];

export const liver: Analyte[] = [
  enzyme('ast', 'AST (GOT)', [
    'Transaminasi AST (GOT)',
    'AST',
    'GOT',
    'SGOT',
    'AST (GOT)',
    'Aspartato aminotransferasi',
  ]),
  enzyme('alt', 'ALT (GPT)', [
    'Transaminasi ALT (GPT)',
    'ALT',
    'GPT',
    'SGPT',
    'ALT (GPT)',
    'Alanina aminotransferasi',
  ]),
  enzyme('ggt', 'Gamma-GT', ['Gamma-GT', 'Gamma GT', 'GGT', 'Gammaglutamiltransferasi']),
  enzyme('alp', 'Fosfatasi alcalina', ['Fosfatasi alcalina', 'ALP']),
  enzyme('ldh', 'LDH', ['LDH', 'Lattato deidrogenasi', 'Latticodeidrogenasi']),
  {
    id: 'bilirubin-total',
    name: 'Bilirubina totale',
    aliases: ['Bilirubina totale', 'Bilirubina', 'Bilirubinemia totale'],
    category: 'epatica',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mg/dL',
    units: BILIRUBIN_UNITS,
  },
  {
    id: 'bilirubin-direct',
    name: 'Bilirubina diretta',
    aliases: ['Bilirubina diretta', 'Bilirubina coniugata'],
    category: 'epatica',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mg/dL',
    units: BILIRUBIN_UNITS,
  },
  {
    id: 'bilirubin-indirect',
    name: 'Bilirubina indiretta',
    aliases: ['Bilirubina indiretta', 'Bilirubina non coniugata'],
    category: 'epatica',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mg/dL',
    units: BILIRUBIN_UNITS,
  },
];

export const thyroid: Analyte[] = [
  {
    id: 'tsh',
    name: 'TSH',
    aliases: ['TSH', 'TSH Reflex', 'Tireotropina', 'Ormone tireostimolante'],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'µUI/mL',
    units: [{ unit: 'mUI/L', toCanonical: 1 }],
  },
  // FT4: 1 pg/mL = 0.1 ng/dL; 1 pmol/L = 0.0777 ng/dL
  {
    id: 'ft4',
    name: 'FT4',
    aliases: ['FT4', 'Tiroxina libera', 'T4 libero', 'T4 libera'],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/dL',
    units: [
      { unit: 'pg/mL', toCanonical: 0.1 },
      { unit: 'pmol/L', toCanonical: 0.0777 },
    ],
  },
  // FT3: 1 pmol/L = 0.651 pg/mL
  {
    id: 'ft3',
    name: 'FT3',
    aliases: ['FT3', 'Triiodotironina libera', 'T3 libero', 'T3 libera'],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
    units: [{ unit: 'pmol/L', toCanonical: 0.651 }],
  },
  {
    id: 'thyroglobulin',
    name: 'Tireoglobulina',
    aliases: ['Tireoglobulina', 'HTG', 'TG'],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'µg/L', toCanonical: 1 }],
  },
  {
    id: 'anti-tpo',
    name: 'Anticorpi anti tireoperossidasi',
    aliases: [
      'Anticorpi anti Tireoperossidasi',
      'Ab-anti Perossidasi (Ab-TPO)',
      'Ab-TPO',
      'Anti-TPO',
      'Anticorpi anti TPO',
    ],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'UI/mL',
  },
  {
    id: 'anti-tg',
    name: 'Anticorpi anti tireoglobulina',
    aliases: [
      'Anticorpi anti Tireoglobulina',
      'Ab-anti Tireoglobulina (Ab-HTG)',
      'Ab-HTG',
      'Anti-TG',
      'Anticorpi anti TG',
    ],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'UI/mL',
  },
  {
    id: 'anti-tshr',
    name: 'Anticorpi anti recettore del TSH',
    aliases: [
      'Anticorpi anti Recettore del TSH',
      'Ab-anti recettore del TSH',
      'TRAb',
      'Anti recettore TSH',
    ],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'U/L',
  },
  {
    id: 'calcitonin',
    name: 'Calcitonina',
    aliases: ['Calcitonina'],
    category: 'tiroide',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
  },
];

export const hormones: Analyte[] = [
  // testosterone: 1 ng/dL = 0.01 ng/mL; 1 nmol/L = 0.2884 ng/mL
  {
    id: 'testosterone-total',
    name: 'Testosterone totale',
    aliases: ['Testosterone', 'Testosterone totale'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [
      { unit: 'ng/dL', toCanonical: 0.01 },
      { unit: 'nmol/L', toCanonical: 0.2884 },
    ],
  },
  {
    id: 'testosterone-free',
    name: 'Testosterone libero',
    aliases: ['Testosterone libero'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
  },
  {
    id: 'shbg',
    name: 'SHBG',
    aliases: ['SHBG', 'Globulina legante gli ormoni sessuali'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'nmol/L',
  },
  // cortisol: 1 nmol/L = 0.03625 µg/dL
  {
    id: 'cortisol',
    name: 'Cortisolo',
    aliases: ['Cortisolo', 'Cortisolemia', 'Cortisolo ore 8'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'µg/dL',
    units: [{ unit: 'nmol/L', toCanonical: 0.03625 }],
  },
  {
    id: 'prolactin',
    name: 'Prolattina',
    aliases: ['Prolattina', 'PRL'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'µg/L', toCanonical: 1 }],
  },
  // estradiol: 1 pmol/L = 0.2724 pg/mL
  {
    id: 'estradiol',
    name: 'Estradiolo',
    aliases: ['Estradiolo', '17 beta estradiolo', 'E2'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
    units: [{ unit: 'pmol/L', toCanonical: 0.2724 }],
  },
  // progesterone: 1 nmol/L = 0.3145 ng/mL
  {
    id: 'progesterone',
    name: 'Progesterone',
    aliases: ['Progesterone'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'ng/mL',
    units: [{ unit: 'nmol/L', toCanonical: 0.3145 }],
  },
  {
    id: 'lh',
    name: 'LH',
    aliases: ['LH', 'Ormone luteinizzante'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mUI/mL',
    units: [{ unit: 'U/L', toCanonical: 1 }],
  },
  {
    id: 'fsh',
    name: 'FSH',
    aliases: ['FSH', 'Ormone follicolo stimolante'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'mUI/mL',
    units: [{ unit: 'U/L', toCanonical: 1 }],
  },
  {
    id: 'dhea-s',
    name: 'DHEA-S',
    aliases: ['DHEA-S', 'DHEAS', 'Deidroepiandrosterone solfato'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'µg/dL',
  },
  {
    id: 'pth',
    name: 'Paratormone',
    aliases: ['Paratormone', 'PTH', 'PTH intatto'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
  },
  {
    id: 'acth',
    name: 'ACTH',
    aliases: ['ACTH', 'Corticotropina'],
    category: 'ormoni',
    specimen: 'blood',
    kind: 'numeric',
    canonicalUnit: 'pg/mL',
  },
];
